import os
from dotenv import load_dotenv
load_dotenv()

# --- Configuration ---
MAX_WINDOW_SIZE = 900
SIDEBAR_WIDTH = 250

WINDOW_WIDTH = MAX_WINDOW_SIZE + SIDEBAR_WIDTH
WINDOW_HEIGHT = MAX_WINDOW_SIZE
GRID_SIZE = 3

FLASH_TIME_MS = 100
MAX_VIDEO_FRAMES = 600000

VIDEO_STREAM_CACHE_FRAMES = 72
PLAYBACK_PREFETCH_BACKWARD_RADIUS = 3
PLAYBACK_PREFETCH_FORWARD_RADIUS = 12
SEEK_PREVIEW_PREFETCH_BACKWARD_RADIUS = 12
SEEK_PREVIEW_PREFETCH_FORWARD_RADIUS = 32
SEEK_PREVIEW_SHEET_BACKWARD_RADIUS = 8
SEEK_PREVIEW_SHEET_FORWARD_RADIUS = 16

NETWORK_TIMEOUT = 20
DOWNLOAD_TIMEOUT = 30

VALID_EXT = {'.png', '.jpg', '.jpeg', '.gif', '.webp', '.mp4'}
CUSTOM_PATH = None

# --- API Configuration ---
PEXELS_API_KEY = os.getenv("PEXELS_API_KEY")


# --- BG/text Configuration ---
BG_MAIN = (24, 25, 28)
BG_PUZZLE = (30, 32, 37)
TEXT_COLOR = (220, 223, 228)

# --- Game Panel Layout ---
GAME_PANEL_MARGIN = 16

SIDEBAR_PANEL_X = GAME_PANEL_MARGIN
SIDEBAR_PANEL_Y = GAME_PANEL_MARGIN
SIDEBAR_PANEL_WIDTH = SIDEBAR_WIDTH - (GAME_PANEL_MARGIN * 2)
SIDEBAR_PANEL_HEIGHT = WINDOW_HEIGHT - (GAME_PANEL_MARGIN * 2)

PUZZLE_PANEL_X = SIDEBAR_WIDTH + GAME_PANEL_MARGIN
PUZZLE_PANEL_Y = GAME_PANEL_MARGIN
PUZZLE_PANEL_WIDTH = WINDOW_WIDTH - PUZZLE_PANEL_X - GAME_PANEL_MARGIN
PUZZLE_PANEL_HEIGHT = WINDOW_HEIGHT - (GAME_PANEL_MARGIN * 2)
PUZZLE_FOOTER_HEIGHT = 62
PUZZLE_CONTENT_PADDING = 18

PUZZLE_AREA_X = PUZZLE_PANEL_X + PUZZLE_CONTENT_PADDING
PUZZLE_AREA_Y = PUZZLE_PANEL_Y + PUZZLE_CONTENT_PADDING
PUZZLE_AREA_WIDTH = PUZZLE_PANEL_WIDTH - (PUZZLE_CONTENT_PADDING * 2)
PUZZLE_AREA_HEIGHT = PUZZLE_PANEL_HEIGHT - PUZZLE_FOOTER_HEIGHT - (PUZZLE_CONTENT_PADDING * 2)

CONTROL_X = SIDEBAR_PANEL_X + 12
CONTROL_WIDTH = SIDEBAR_PANEL_WIDTH - 24

# --- Win Button Configuration ---
WIN_BUTTON_X = CONTROL_X
WIN_BUTTON_Y = 124
WIN_BUTTON_WIDTH = CONTROL_WIDTH
WIN_BUTTON_HEIGHT = 54

WIN_BUTTON_COLOR = (82, 126, 212)
WIN_BUTTON_PRESS_COLOR = (58, 92, 166)
WIN_BUTTON_BORDER = (128, 166, 240)
WIN_BUTTON_PRESS_BORDER = (96, 132, 212)

# --- Skip Button Configuration ---
SKIP_BUTTON_X = CONTROL_X
SKIP_BUTTON_Y = WIN_BUTTON_Y
SKIP_BUTTON_WIDTH = CONTROL_WIDTH
SKIP_BUTTON_HEIGHT = WIN_BUTTON_HEIGHT

SKIP_BUTTON_COLOR = WIN_BUTTON_COLOR
SKIP_BUTTON_PRESS_COLOR = WIN_BUTTON_PRESS_COLOR
SKIP_BUTTON_BORDER = WIN_BUTTON_BORDER
SKIP_BUTTON_PRESS_BORDER = WIN_BUTTON_PRESS_BORDER

# --- Save Button Configuration ---
SAVE_BUTTON_X = CONTROL_X
SAVE_BUTTON_Y = 192
SAVE_BUTTON_WIDTH = CONTROL_WIDTH
SAVE_BUTTON_HEIGHT = 54

SAVE_BUTTON_COLOR = (42, 46, 53)
SAVE_BUTTON_PRESS_COLOR = (37, 41, 47)
SAVE_BUTTON_BORDER = (82, 88, 97)
SAVE_BUTTON_PRESS_BORDER = (68, 74, 84)

# --- Menu Button Configuration ---
MENU_BUTTON_X = CONTROL_X
MENU_BUTTON_Y = SIDEBAR_PANEL_Y + SIDEBAR_PANEL_HEIGHT - 70
MENU_BUTTON_WIDTH = CONTROL_WIDTH
MENU_BUTTON_HEIGHT = 54

MENU_BUTTON_COLOR = SAVE_BUTTON_COLOR
MENU_BUTTON_PRESS_COLOR = SAVE_BUTTON_PRESS_COLOR
MENU_BUTTON_BORDER = SAVE_BUTTON_BORDER

# --- Tile Configuration ---
TILE_BORDER_COLOR = (82, 88, 97, 180)
CORRECT_FLASH_COLOR = (120, 170, 255)  
CORRECT_FLASH_BORDER_COLOR = (120, 170, 255, 70)
INCORRECT_FLASH_COLOR = (68, 74, 84)
INCORRECT_FLASH_BORDER_COLOR = (90, 95, 100, 140)

# --- TextBox Configuration ---
TEXTBOX_X = CONTROL_X
TEXTBOX_Y = 312
TEXTBOX_WIDTH = CONTROL_WIDTH
TEXTBOX_HEIGHT = 42

TEXTBOX_COLOR_ACTIVE = CORRECT_FLASH_COLOR
TEXTBOX_COLOR_INACTIVE = (82, 88, 97)
TEXTBOX_SELECTION_COLOR = (56, 72, 108)
TEXTBOX_BG_COLOR = (42, 46, 53)

# --- Volume Slider Configuration ---
SLIDER_X = CONTROL_X
SLIDER_Y = 428
SLIDER_WIDTH = CONTROL_WIDTH
SLIDER_HEIGHT = 10
SLIDER_KNOB_RADIUS = 9

SLIDER_BG_COLOR = (56, 60, 68)
SLIDER_FILL_COLOR = WIN_BUTTON_COLOR
SLIDER_KNOB_COLOR = TEXT_COLOR
INITIAL_VOLUME = 0.1

# --- Seek Bar Configuration --- 
SEEKBAR_X = PUZZLE_PANEL_X + 24
SEEKBAR_HEIGHT = 8
SEEKBAR_Y = PUZZLE_PANEL_Y + PUZZLE_PANEL_HEIGHT - 35
SEEKBAR_WIDTH = PUZZLE_PANEL_WIDTH - 48

SEEKBAR_BG_COLOR = (56, 60, 68)
SEEKBAR_FILL_COLOR = WIN_BUTTON_COLOR
SEEKBAR_KNOB_COLOR = TEXT_COLOR
SEEK_PREVIEW_WIDTH = 176
SEEK_PREVIEW_HEIGHT = 118
SEEK_PREVIEW_FOOTER_HEIGHT = 26
SEEK_PREVIEW_GAP = 14
SEEK_PREVIEW_SHEET_THUMBS = 25
SEEK_PREVIEW_SHEET_COLUMNS = 5
SEEK_PREVIEW_CACHE_SHEETS = 4

# --- Main Menu Configuration ---
MENU_INFO_X = 60
MENU_INFO_Y = 100
MENU_INFO_WIDTH = 300
MENU_START_MIN_Y = 400
MENU_STATUS_SPACING = 28

MENU_GRID_X = 410
MENU_GRID_Y = 170
MENU_CARD_WIDTH = 320
MENU_CARD_HEIGHT = 150
MENU_CARD_GAP = 24

TAB_Y = MENU_GRID_Y - 72
TAB_W = 140
TAB_H = 42

MENU_PANEL_COLOR = (30, 32, 37)
MENU_PANEL_BORDER = (56, 60, 68)
MENU_CARD_COLOR = (42, 46, 53)
MENU_CARD_HOVER_COLOR = (50, 55, 63)
MENU_CARD_PRESS_COLOR = (37, 41, 47)
MENU_CARD_BORDER = (82, 88, 97)
MENU_CARD_SELECTED_COLOR = (56, 72, 108)
MENU_CARD_SELECTED_BORDER = (120, 155, 235)
MENU_SUBTEXT_COLOR = (156, 162, 172)
MENU_ERROR_COLOR = (235, 120, 108)
MENU_START_BUTTON_COLOR = (82, 126, 212)
MENU_START_BUTTON_PRESS_COLOR = (58, 92, 166)
MENU_START_BUTTON_BORDER = (128, 166, 240)
